# Generated by Django 4.1 on 2022-09-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0003_alter_category_options_alter_film_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to="images/%Y/%m/%d/", verbose_name="Фото"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Заголовок"
                    ),
                ),
            ],
            options={
                "verbose_name": "Реклама",
                "verbose_name_plural": "Реклама",
                "ordering": ["title"],
            },
        ),
        migrations.AlterField(
            model_name="film",
            name="category",
            field=models.ManyToManyField(to="index.category", verbose_name="Жанр"),
        ),
        migrations.AlterField(
            model_name="film",
            name="date",
            field=models.IntegerField(verbose_name="Дата выхода"),
        ),
    ]
