# Generated by Django 4.1 on 2022-09-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0005_alter_film_category_alter_film_player"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=200, verbose_name="Имя"),
                ),
                (
                    "surname",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Фамилия"
                    ),
                ),
                (
                    "age",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Возраст"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to="images/artists/%Y/%m/%d", verbose_name="Фотография"
                    ),
                ),
            ],
            options={"verbose_name": "Актер", "verbose_name_plural": "Актеры",},
        ),
        migrations.AddField(
            model_name="film",
            name="artists",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="films", to="index.artist"
            ),
        ),
    ]
