# Generated by Django 4.1 on 2022-09-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0006_artist_film_artists"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artist",
            options={
                "ordering": ["name"],
                "verbose_name": "Актер",
                "verbose_name_plural": "Актеры",
            },
        ),
        migrations.AddField(
            model_name="artist",
            name="country",
            field=models.CharField(blank=True, max_length=199, verbose_name="Страна"),
        ),
        migrations.AddField(
            model_name="film",
            name="country",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Страна"
            ),
        ),
    ]
