# Generated by Django 4.1 on 2022-09-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0007_alter_artist_options_artist_country_film_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="film",
            name="rating",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Рейтинг"
            ),
        ),
    ]
