# Generated by Django 4.1 on 2022-09-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0009_film_year_in_school"),
    ]

    operations = [
        migrations.RemoveField(model_name="film", name="year_in_school",),
        migrations.AlterField(
            model_name="film",
            name="rating",
            field=models.CharField(
                blank=True,
                choices=[("PG0", "0+"), ("PG12", "12+"), ("PG18", "18+")],
                default="PG0",
                max_length=200,
                null=True,
                verbose_name="Рейтинг",
            ),
        ),
    ]
