# Generated by Django 4.1 on 2022-09-09 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0011_alter_film_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=299, verbose_name="Имя")),
                ("surname", models.CharField(max_length=299, verbose_name="Фамилия")),
            ],
        ),
        migrations.AddField(
            model_name="film",
            name="director",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="films",
                to="index.director",
            ),
        ),
    ]
