# Generated by Django 4.1 on 2022-09-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0012_director_film_director"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=140, verbose_name="Название жанра"
                    ),
                ),
                (
                    "content",
                    models.CharField(
                        blank=True, max_length=140, verbose_name="Описание жанра"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=200, null=True, unique=True, verbose_name="URL"
                    ),
                ),
            ],
            options={
                "verbose_name": "Жанр",
                "verbose_name_plural": "Жанры",
                "ordering": ["title"],
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["title"],
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AlterModelOptions(
            name="director",
            options={
                "ordering": ["name"],
                "verbose_name": "Режиссер",
                "verbose_name_plural": "Режжисеры",
            },
        ),
        migrations.AlterField(
            model_name="film",
            name="date",
            field=models.IntegerField(blank=True, verbose_name="Дата выхода"),
        ),
        migrations.AlterField(
            model_name="film",
            name="photo",
            field=models.ImageField(
                blank=True, upload_to="images/%Y/%m/%d/", verbose_name="Картинка"
            ),
        ),
    ]
