# Generated by Django 4.1 on 2022-09-10 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0013_genre_alter_category_options_alter_director_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="director",
            options={
                "ordering": ["name"],
                "verbose_name": "Режиссер",
                "verbose_name_plural": "Режиссеры",
            },
        ),
        migrations.AddField(
            model_name="film",
            name="genre",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="films", to="index.genre"
            ),
        ),
        migrations.RemoveField(model_name="film", name="category",),
        migrations.AddField(
            model_name="film",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="films",
                to="index.category",
                verbose_name="Категория",
            ),
        ),
    ]
