# Generated by Django 4.1 on 2022-09-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0014_alter_director_options_film_genre_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="film",
            name="meta_description",
            field=models.CharField(
                blank=True, max_length=299, verbose_name="meta_description"
            ),
        ),
        migrations.AddField(
            model_name="film",
            name="meta_keyword",
            field=models.CharField(
                blank=True, max_length=299, verbose_name="meta_keyword"
            ),
        ),
    ]
